// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	ACLKeyAccess    string
	Alarm           string
	AlarmCFG        string
	AlarmHistory    string
	Asset           string
	AssetType       string
	AttributeSchema string
	Currency        string
	Dashboard       string
	EdgeBridge      string
	ElionaApp       string
	ElionaNode      string
	Heap            string
	IosysAccess     string
	IosysDevice     string
	Keyauth         string
	MbusAccess      string
	MbusDevice      string
	Widget          string
	WidgetData      string
	WidgetElement   string
	WidgetType      string
}{
	ACLKeyAccess:    "acl_key_access",
	Alarm:           "alarm",
	AlarmCFG:        "alarm_cfg",
	AlarmHistory:    "alarm_history",
	Asset:           "asset",
	AssetType:       "asset_type",
	AttributeSchema: "attribute_schema",
	Currency:        "currency",
	Dashboard:       "dashboard",
	EdgeBridge:      "edge_bridge",
	ElionaApp:       "eliona_app",
	ElionaNode:      "eliona_node",
	Heap:            "heap",
	IosysAccess:     "iosys_access",
	IosysDevice:     "iosys_device",
	Keyauth:         "keyauth",
	MbusAccess:      "mbus_access",
	MbusDevice:      "mbus_device",
	Widget:          "widget",
	WidgetData:      "widget_data",
	WidgetElement:   "widget_element",
	WidgetType:      "widget_type",
}
