// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// ElionaNode is an object representing the database table.
type ElionaNode struct {
	NodeID      string      `boil:"node_id" json:"node_id" toml:"node_id" yaml:"node_id"`
	Ident       string      `boil:"ident" json:"ident" toml:"ident" yaml:"ident"`
	Password    null.String `boil:"password" json:"password,omitempty" toml:"password" yaml:"password,omitempty"`
	AssetID     null.Int    `boil:"asset_id" json:"asset_id,omitempty" toml:"asset_id" yaml:"asset_id,omitempty"`
	Vendor      null.String `boil:"vendor" json:"vendor,omitempty" toml:"vendor" yaml:"vendor,omitempty"`
	Model       null.String `boil:"model" json:"model,omitempty" toml:"model" yaml:"model,omitempty"`
	Description null.String `boil:"description" json:"description,omitempty" toml:"description" yaml:"description,omitempty"`
	Enable      bool        `boil:"enable" json:"enable" toml:"enable" yaml:"enable"`

	R *elionaNodeR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L elionaNodeL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ElionaNodeColumns = struct {
	NodeID      string
	Ident       string
	Password    string
	AssetID     string
	Vendor      string
	Model       string
	Description string
	Enable      string
}{
	NodeID:      "node_id",
	Ident:       "ident",
	Password:    "password",
	AssetID:     "asset_id",
	Vendor:      "vendor",
	Model:       "model",
	Description: "description",
	Enable:      "enable",
}

var ElionaNodeTableColumns = struct {
	NodeID      string
	Ident       string
	Password    string
	AssetID     string
	Vendor      string
	Model       string
	Description string
	Enable      string
}{
	NodeID:      "eliona_node.node_id",
	Ident:       "eliona_node.ident",
	Password:    "eliona_node.password",
	AssetID:     "eliona_node.asset_id",
	Vendor:      "eliona_node.vendor",
	Model:       "eliona_node.model",
	Description: "eliona_node.description",
	Enable:      "eliona_node.enable",
}

// Generated where

var ElionaNodeWhere = struct {
	NodeID      whereHelperstring
	Ident       whereHelperstring
	Password    whereHelpernull_String
	AssetID     whereHelpernull_Int
	Vendor      whereHelpernull_String
	Model       whereHelpernull_String
	Description whereHelpernull_String
	Enable      whereHelperbool
}{
	NodeID:      whereHelperstring{field: "\"eliona_node\".\"node_id\""},
	Ident:       whereHelperstring{field: "\"eliona_node\".\"ident\""},
	Password:    whereHelpernull_String{field: "\"eliona_node\".\"password\""},
	AssetID:     whereHelpernull_Int{field: "\"eliona_node\".\"asset_id\""},
	Vendor:      whereHelpernull_String{field: "\"eliona_node\".\"vendor\""},
	Model:       whereHelpernull_String{field: "\"eliona_node\".\"model\""},
	Description: whereHelpernull_String{field: "\"eliona_node\".\"description\""},
	Enable:      whereHelperbool{field: "\"eliona_node\".\"enable\""},
}

// ElionaNodeRels is where relationship names are stored.
var ElionaNodeRels = struct {
}{}

// elionaNodeR is where relationships are stored.
type elionaNodeR struct {
}

// NewStruct creates a new relationship struct
func (*elionaNodeR) NewStruct() *elionaNodeR {
	return &elionaNodeR{}
}

// elionaNodeL is where Load methods for each relationship are stored.
type elionaNodeL struct{}

var (
	elionaNodeAllColumns            = []string{"node_id", "ident", "password", "asset_id", "vendor", "model", "description", "enable"}
	elionaNodeColumnsWithoutDefault = []string{"node_id"}
	elionaNodeColumnsWithDefault    = []string{"ident", "password", "asset_id", "vendor", "model", "description", "enable"}
	elionaNodePrimaryKeyColumns     = []string{"node_id"}
	elionaNodeGeneratedColumns      = []string{}
)

type (
	// ElionaNodeSlice is an alias for a slice of pointers to ElionaNode.
	// This should almost always be used instead of []ElionaNode.
	ElionaNodeSlice []*ElionaNode
	// ElionaNodeHook is the signature for custom ElionaNode hook methods
	ElionaNodeHook func(context.Context, boil.ContextExecutor, *ElionaNode) error

	elionaNodeQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	elionaNodeType                 = reflect.TypeOf(&ElionaNode{})
	elionaNodeMapping              = queries.MakeStructMapping(elionaNodeType)
	elionaNodePrimaryKeyMapping, _ = queries.BindMapping(elionaNodeType, elionaNodeMapping, elionaNodePrimaryKeyColumns)
	elionaNodeInsertCacheMut       sync.RWMutex
	elionaNodeInsertCache          = make(map[string]insertCache)
	elionaNodeUpdateCacheMut       sync.RWMutex
	elionaNodeUpdateCache          = make(map[string]updateCache)
	elionaNodeUpsertCacheMut       sync.RWMutex
	elionaNodeUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var elionaNodeAfterSelectHooks []ElionaNodeHook

var elionaNodeBeforeInsertHooks []ElionaNodeHook
var elionaNodeAfterInsertHooks []ElionaNodeHook

var elionaNodeBeforeUpdateHooks []ElionaNodeHook
var elionaNodeAfterUpdateHooks []ElionaNodeHook

var elionaNodeBeforeDeleteHooks []ElionaNodeHook
var elionaNodeAfterDeleteHooks []ElionaNodeHook

var elionaNodeBeforeUpsertHooks []ElionaNodeHook
var elionaNodeAfterUpsertHooks []ElionaNodeHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *ElionaNode) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range elionaNodeAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *ElionaNode) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range elionaNodeBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *ElionaNode) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range elionaNodeAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *ElionaNode) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range elionaNodeBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *ElionaNode) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range elionaNodeAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *ElionaNode) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range elionaNodeBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *ElionaNode) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range elionaNodeAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *ElionaNode) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range elionaNodeBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *ElionaNode) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range elionaNodeAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddElionaNodeHook registers your hook function for all future operations.
func AddElionaNodeHook(hookPoint boil.HookPoint, elionaNodeHook ElionaNodeHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		elionaNodeAfterSelectHooks = append(elionaNodeAfterSelectHooks, elionaNodeHook)
	case boil.BeforeInsertHook:
		elionaNodeBeforeInsertHooks = append(elionaNodeBeforeInsertHooks, elionaNodeHook)
	case boil.AfterInsertHook:
		elionaNodeAfterInsertHooks = append(elionaNodeAfterInsertHooks, elionaNodeHook)
	case boil.BeforeUpdateHook:
		elionaNodeBeforeUpdateHooks = append(elionaNodeBeforeUpdateHooks, elionaNodeHook)
	case boil.AfterUpdateHook:
		elionaNodeAfterUpdateHooks = append(elionaNodeAfterUpdateHooks, elionaNodeHook)
	case boil.BeforeDeleteHook:
		elionaNodeBeforeDeleteHooks = append(elionaNodeBeforeDeleteHooks, elionaNodeHook)
	case boil.AfterDeleteHook:
		elionaNodeAfterDeleteHooks = append(elionaNodeAfterDeleteHooks, elionaNodeHook)
	case boil.BeforeUpsertHook:
		elionaNodeBeforeUpsertHooks = append(elionaNodeBeforeUpsertHooks, elionaNodeHook)
	case boil.AfterUpsertHook:
		elionaNodeAfterUpsertHooks = append(elionaNodeAfterUpsertHooks, elionaNodeHook)
	}
}

// One returns a single elionaNode record from the query.
func (q elionaNodeQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ElionaNode, error) {
	o := &ElionaNode{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for eliona_node")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all ElionaNode records from the query.
func (q elionaNodeQuery) All(ctx context.Context, exec boil.ContextExecutor) (ElionaNodeSlice, error) {
	var o []*ElionaNode

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to ElionaNode slice")
	}

	if len(elionaNodeAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all ElionaNode records in the query.
func (q elionaNodeQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count eliona_node rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q elionaNodeQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if eliona_node exists")
	}

	return count > 0, nil
}

// ElionaNodes retrieves all the records using an executor.
func ElionaNodes(mods ...qm.QueryMod) elionaNodeQuery {
	mods = append(mods, qm.From("\"eliona_node\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"eliona_node\".*"})
	}

	return elionaNodeQuery{q}
}

// FindElionaNode retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindElionaNode(ctx context.Context, exec boil.ContextExecutor, nodeID string, selectCols ...string) (*ElionaNode, error) {
	elionaNodeObj := &ElionaNode{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"eliona_node\" where \"node_id\"=$1", sel,
	)

	q := queries.Raw(query, nodeID)

	err := q.Bind(ctx, exec, elionaNodeObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from eliona_node")
	}

	if err = elionaNodeObj.doAfterSelectHooks(ctx, exec); err != nil {
		return elionaNodeObj, err
	}

	return elionaNodeObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ElionaNode) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no eliona_node provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(elionaNodeColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	elionaNodeInsertCacheMut.RLock()
	cache, cached := elionaNodeInsertCache[key]
	elionaNodeInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			elionaNodeAllColumns,
			elionaNodeColumnsWithDefault,
			elionaNodeColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(elionaNodeType, elionaNodeMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(elionaNodeType, elionaNodeMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"eliona_node\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"eliona_node\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into eliona_node")
	}

	if !cached {
		elionaNodeInsertCacheMut.Lock()
		elionaNodeInsertCache[key] = cache
		elionaNodeInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the ElionaNode.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ElionaNode) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	elionaNodeUpdateCacheMut.RLock()
	cache, cached := elionaNodeUpdateCache[key]
	elionaNodeUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			elionaNodeAllColumns,
			elionaNodePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update eliona_node, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"eliona_node\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, elionaNodePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(elionaNodeType, elionaNodeMapping, append(wl, elionaNodePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update eliona_node row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for eliona_node")
	}

	if !cached {
		elionaNodeUpdateCacheMut.Lock()
		elionaNodeUpdateCache[key] = cache
		elionaNodeUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q elionaNodeQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for eliona_node")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for eliona_node")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ElionaNodeSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), elionaNodePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"eliona_node\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, elionaNodePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in elionaNode slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all elionaNode")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ElionaNode) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no eliona_node provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(elionaNodeColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	elionaNodeUpsertCacheMut.RLock()
	cache, cached := elionaNodeUpsertCache[key]
	elionaNodeUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			elionaNodeAllColumns,
			elionaNodeColumnsWithDefault,
			elionaNodeColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			elionaNodeAllColumns,
			elionaNodePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert eliona_node, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(elionaNodePrimaryKeyColumns))
			copy(conflict, elionaNodePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"eliona_node\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(elionaNodeType, elionaNodeMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(elionaNodeType, elionaNodeMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert eliona_node")
	}

	if !cached {
		elionaNodeUpsertCacheMut.Lock()
		elionaNodeUpsertCache[key] = cache
		elionaNodeUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single ElionaNode record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ElionaNode) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no ElionaNode provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), elionaNodePrimaryKeyMapping)
	sql := "DELETE FROM \"eliona_node\" WHERE \"node_id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from eliona_node")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for eliona_node")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q elionaNodeQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no elionaNodeQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from eliona_node")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for eliona_node")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ElionaNodeSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(elionaNodeBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), elionaNodePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"eliona_node\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, elionaNodePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from elionaNode slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for eliona_node")
	}

	if len(elionaNodeAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ElionaNode) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindElionaNode(ctx, exec, o.NodeID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ElionaNodeSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ElionaNodeSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), elionaNodePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"eliona_node\".* FROM \"eliona_node\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, elionaNodePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ElionaNodeSlice")
	}

	*o = slice

	return nil
}

// ElionaNodeExists checks if the ElionaNode row exists.
func ElionaNodeExists(ctx context.Context, exec boil.ContextExecutor, nodeID string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"eliona_node\" where \"node_id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, nodeID)
	}
	row := exec.QueryRowContext(ctx, sql, nodeID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if eliona_node exists")
	}

	return exists, nil
}
