// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// WidgetDatum is an object representing the database table.
type WidgetDatum struct {
	WidgetID        int       `boil:"widget_id" json:"widget_id" toml:"widget_id" yaml:"widget_id"`
	WidgetElementID int       `boil:"widget_element_id" json:"widget_element_id" toml:"widget_element_id" yaml:"widget_element_id"`
	AssetID         null.Int  `boil:"asset_id" json:"asset_id,omitempty" toml:"asset_id" yaml:"asset_id,omitempty"`
	Data            null.JSON `boil:"data" json:"data,omitempty" toml:"data" yaml:"data,omitempty"`
	ID              int       `boil:"id" json:"id" toml:"id" yaml:"id"`

	R *widgetDatumR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L widgetDatumL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var WidgetDatumColumns = struct {
	WidgetID        string
	WidgetElementID string
	AssetID         string
	Data            string
	ID              string
}{
	WidgetID:        "widget_id",
	WidgetElementID: "widget_element_id",
	AssetID:         "asset_id",
	Data:            "data",
	ID:              "id",
}

var WidgetDatumTableColumns = struct {
	WidgetID        string
	WidgetElementID string
	AssetID         string
	Data            string
	ID              string
}{
	WidgetID:        "widget_data.widget_id",
	WidgetElementID: "widget_data.widget_element_id",
	AssetID:         "widget_data.asset_id",
	Data:            "widget_data.data",
	ID:              "widget_data.id",
}

// Generated where

var WidgetDatumWhere = struct {
	WidgetID        whereHelperint
	WidgetElementID whereHelperint
	AssetID         whereHelpernull_Int
	Data            whereHelpernull_JSON
	ID              whereHelperint
}{
	WidgetID:        whereHelperint{field: "\"widget_data\".\"widget_id\""},
	WidgetElementID: whereHelperint{field: "\"widget_data\".\"widget_element_id\""},
	AssetID:         whereHelpernull_Int{field: "\"widget_data\".\"asset_id\""},
	Data:            whereHelpernull_JSON{field: "\"widget_data\".\"data\""},
	ID:              whereHelperint{field: "\"widget_data\".\"id\""},
}

// WidgetDatumRels is where relationship names are stored.
var WidgetDatumRels = struct {
}{}

// widgetDatumR is where relationships are stored.
type widgetDatumR struct {
}

// NewStruct creates a new relationship struct
func (*widgetDatumR) NewStruct() *widgetDatumR {
	return &widgetDatumR{}
}

// widgetDatumL is where Load methods for each relationship are stored.
type widgetDatumL struct{}

var (
	widgetDatumAllColumns            = []string{"widget_id", "widget_element_id", "asset_id", "data", "id"}
	widgetDatumColumnsWithoutDefault = []string{"widget_id", "widget_element_id"}
	widgetDatumColumnsWithDefault    = []string{"asset_id", "data", "id"}
	widgetDatumPrimaryKeyColumns     = []string{"id"}
	widgetDatumGeneratedColumns      = []string{}
)

type (
	// WidgetDatumSlice is an alias for a slice of pointers to WidgetDatum.
	// This should almost always be used instead of []WidgetDatum.
	WidgetDatumSlice []*WidgetDatum
	// WidgetDatumHook is the signature for custom WidgetDatum hook methods
	WidgetDatumHook func(context.Context, boil.ContextExecutor, *WidgetDatum) error

	widgetDatumQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	widgetDatumType                 = reflect.TypeOf(&WidgetDatum{})
	widgetDatumMapping              = queries.MakeStructMapping(widgetDatumType)
	widgetDatumPrimaryKeyMapping, _ = queries.BindMapping(widgetDatumType, widgetDatumMapping, widgetDatumPrimaryKeyColumns)
	widgetDatumInsertCacheMut       sync.RWMutex
	widgetDatumInsertCache          = make(map[string]insertCache)
	widgetDatumUpdateCacheMut       sync.RWMutex
	widgetDatumUpdateCache          = make(map[string]updateCache)
	widgetDatumUpsertCacheMut       sync.RWMutex
	widgetDatumUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var widgetDatumAfterSelectHooks []WidgetDatumHook

var widgetDatumBeforeInsertHooks []WidgetDatumHook
var widgetDatumAfterInsertHooks []WidgetDatumHook

var widgetDatumBeforeUpdateHooks []WidgetDatumHook
var widgetDatumAfterUpdateHooks []WidgetDatumHook

var widgetDatumBeforeDeleteHooks []WidgetDatumHook
var widgetDatumAfterDeleteHooks []WidgetDatumHook

var widgetDatumBeforeUpsertHooks []WidgetDatumHook
var widgetDatumAfterUpsertHooks []WidgetDatumHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *WidgetDatum) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range widgetDatumAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *WidgetDatum) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range widgetDatumBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *WidgetDatum) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range widgetDatumAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *WidgetDatum) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range widgetDatumBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *WidgetDatum) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range widgetDatumAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *WidgetDatum) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range widgetDatumBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *WidgetDatum) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range widgetDatumAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *WidgetDatum) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range widgetDatumBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *WidgetDatum) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range widgetDatumAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddWidgetDatumHook registers your hook function for all future operations.
func AddWidgetDatumHook(hookPoint boil.HookPoint, widgetDatumHook WidgetDatumHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		widgetDatumAfterSelectHooks = append(widgetDatumAfterSelectHooks, widgetDatumHook)
	case boil.BeforeInsertHook:
		widgetDatumBeforeInsertHooks = append(widgetDatumBeforeInsertHooks, widgetDatumHook)
	case boil.AfterInsertHook:
		widgetDatumAfterInsertHooks = append(widgetDatumAfterInsertHooks, widgetDatumHook)
	case boil.BeforeUpdateHook:
		widgetDatumBeforeUpdateHooks = append(widgetDatumBeforeUpdateHooks, widgetDatumHook)
	case boil.AfterUpdateHook:
		widgetDatumAfterUpdateHooks = append(widgetDatumAfterUpdateHooks, widgetDatumHook)
	case boil.BeforeDeleteHook:
		widgetDatumBeforeDeleteHooks = append(widgetDatumBeforeDeleteHooks, widgetDatumHook)
	case boil.AfterDeleteHook:
		widgetDatumAfterDeleteHooks = append(widgetDatumAfterDeleteHooks, widgetDatumHook)
	case boil.BeforeUpsertHook:
		widgetDatumBeforeUpsertHooks = append(widgetDatumBeforeUpsertHooks, widgetDatumHook)
	case boil.AfterUpsertHook:
		widgetDatumAfterUpsertHooks = append(widgetDatumAfterUpsertHooks, widgetDatumHook)
	}
}

// One returns a single widgetDatum record from the query.
func (q widgetDatumQuery) One(ctx context.Context, exec boil.ContextExecutor) (*WidgetDatum, error) {
	o := &WidgetDatum{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for widget_data")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all WidgetDatum records from the query.
func (q widgetDatumQuery) All(ctx context.Context, exec boil.ContextExecutor) (WidgetDatumSlice, error) {
	var o []*WidgetDatum

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to WidgetDatum slice")
	}

	if len(widgetDatumAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all WidgetDatum records in the query.
func (q widgetDatumQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count widget_data rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q widgetDatumQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if widget_data exists")
	}

	return count > 0, nil
}

// WidgetData retrieves all the records using an executor.
func WidgetData(mods ...qm.QueryMod) widgetDatumQuery {
	mods = append(mods, qm.From("\"widget_data\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"widget_data\".*"})
	}

	return widgetDatumQuery{q}
}

// FindWidgetDatum retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindWidgetDatum(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*WidgetDatum, error) {
	widgetDatumObj := &WidgetDatum{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"widget_data\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, widgetDatumObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from widget_data")
	}

	if err = widgetDatumObj.doAfterSelectHooks(ctx, exec); err != nil {
		return widgetDatumObj, err
	}

	return widgetDatumObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *WidgetDatum) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no widget_data provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(widgetDatumColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	widgetDatumInsertCacheMut.RLock()
	cache, cached := widgetDatumInsertCache[key]
	widgetDatumInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			widgetDatumAllColumns,
			widgetDatumColumnsWithDefault,
			widgetDatumColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(widgetDatumType, widgetDatumMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(widgetDatumType, widgetDatumMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"widget_data\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"widget_data\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into widget_data")
	}

	if !cached {
		widgetDatumInsertCacheMut.Lock()
		widgetDatumInsertCache[key] = cache
		widgetDatumInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the WidgetDatum.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *WidgetDatum) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	widgetDatumUpdateCacheMut.RLock()
	cache, cached := widgetDatumUpdateCache[key]
	widgetDatumUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			widgetDatumAllColumns,
			widgetDatumPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update widget_data, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"widget_data\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, widgetDatumPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(widgetDatumType, widgetDatumMapping, append(wl, widgetDatumPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update widget_data row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for widget_data")
	}

	if !cached {
		widgetDatumUpdateCacheMut.Lock()
		widgetDatumUpdateCache[key] = cache
		widgetDatumUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q widgetDatumQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for widget_data")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for widget_data")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o WidgetDatumSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), widgetDatumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"widget_data\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, widgetDatumPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in widgetDatum slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all widgetDatum")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *WidgetDatum) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no widget_data provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(widgetDatumColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	widgetDatumUpsertCacheMut.RLock()
	cache, cached := widgetDatumUpsertCache[key]
	widgetDatumUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			widgetDatumAllColumns,
			widgetDatumColumnsWithDefault,
			widgetDatumColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			widgetDatumAllColumns,
			widgetDatumPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert widget_data, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(widgetDatumPrimaryKeyColumns))
			copy(conflict, widgetDatumPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"widget_data\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(widgetDatumType, widgetDatumMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(widgetDatumType, widgetDatumMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert widget_data")
	}

	if !cached {
		widgetDatumUpsertCacheMut.Lock()
		widgetDatumUpsertCache[key] = cache
		widgetDatumUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single WidgetDatum record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *WidgetDatum) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no WidgetDatum provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), widgetDatumPrimaryKeyMapping)
	sql := "DELETE FROM \"widget_data\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from widget_data")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for widget_data")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q widgetDatumQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no widgetDatumQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from widget_data")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for widget_data")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o WidgetDatumSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(widgetDatumBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), widgetDatumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"widget_data\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, widgetDatumPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from widgetDatum slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for widget_data")
	}

	if len(widgetDatumAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *WidgetDatum) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindWidgetDatum(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *WidgetDatumSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := WidgetDatumSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), widgetDatumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"widget_data\".* FROM \"widget_data\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, widgetDatumPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in WidgetDatumSlice")
	}

	*o = slice

	return nil
}

// WidgetDatumExists checks if the WidgetDatum row exists.
func WidgetDatumExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"widget_data\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if widget_data exists")
	}

	return exists, nil
}
